# -*- coding: utf-8 -*-
"""genAIprelab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xCbCF1Lcdhdc2nRyY9Q5Du-YV7B70WcO
"""

!pip install transformers
from transformers import pipeline

classifier = pipeline("text-classification",model = "cardiffnlp/twitter-roberta-base-sentiment-latest")
classifier("I like this phone! camera quality is good")

classifier("i hate my life")

!pip install gradio
import gradio as gr
from transformers import pipeline
classifier = pipeline("text-classification",model = "cardiffnlp/twitter-roberta-base-sentiment-latest")
def predict_sentiment(text):
  return classifier(text)[0]
gr.Interface(fn = predict_sentiment, inputs = "text", outputs = "text").launch()